version: '3.8'
services:
  grafana:
    image: "grafana/grafana"
    volumes:
      - type: bind
        source: ./grafana/var
        target: /var/lib/grafana
      - type: bind
        source: ./grafana/etc
        target: /etc/grafana
    user: "root"
    ports:
      - "3000:3000"
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - type: bind
        source: ./influxdb/var
        target: /var/lib/influxdb
      - type: bind
        source: ./influxdb/etc
        target: /etc/influxdb
  telegraf:
    image: "telegraf"
    volumes:
      - type: bind
        source: ./telegraf/etc
        target: /etc/telegraf