{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Grafana [errors only]",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"grafana-playground_grafana_1\"} |= \"error\""
    }
   ]
  },
  {
   "title": "Influxdb [errors only]",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"grafana-playground_influxdb_1\"} |= \"error\""
    }
   ]
  },
  {
   "title": "Telegraf [errors only]",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container_name=\"grafana-playground_telegraf_1\"} |= \"error\""
    }
   ]
  }
 ]
}